################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
ASM_UPPER_SRCS := 
C_SRCS := 
ELF_SRCS := 
LSL_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_LIST := 
SECONDARY_SIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Configurations/Debug \
Configurations \
. \
Libraries/Ethernet/Phy_Rtl8211f \
Libraries/Ethernet/lwip/port/src \
Libraries/Ethernet/lwip/src/api \
Libraries/Ethernet/lwip/src/core \
Libraries/Ethernet/lwip/src/core/ipv4 \
Libraries/Ethernet/lwip/src/core/ipv6 \
Libraries/Ethernet/lwip/src/netif \
Libraries/Ethernet/lwip/src/netif/ppp \
Libraries/Ethernet/lwip/src/netif/ppp/polarssl \
Libraries/Infra/Platform/Tricore/Compilers \
Libraries/Infra/Ssw/TC39B/Tricore \
Libraries/Service/CpuGeneric/If \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/Service/CpuGeneric/SysSe/Comm \
Libraries/Service/CpuGeneric/SysSe/General \
Libraries/Service/CpuGeneric/SysSe/Math \
Libraries/Service/CpuGeneric/SysSe/Time \
Libraries/UART \
Libraries/iLLD/TC39B/Tricore/Asclin/Asc \
Libraries/iLLD/TC39B/Tricore/Asclin/Lin \
Libraries/iLLD/TC39B/Tricore/Asclin/Spi \
Libraries/iLLD/TC39B/Tricore/Asclin/Std \
Libraries/iLLD/TC39B/Tricore/Can/Can \
Libraries/iLLD/TC39B/Tricore/Can/Std \
Libraries/iLLD/TC39B/Tricore/Ccu6/Icu \
Libraries/iLLD/TC39B/Tricore/Ccu6/PwmBc \
Libraries/iLLD/TC39B/Tricore/Ccu6/PwmHl \
Libraries/iLLD/TC39B/Tricore/Ccu6/Std \
Libraries/iLLD/TC39B/Tricore/Ccu6/TPwm \
Libraries/iLLD/TC39B/Tricore/Ccu6/Timer \
Libraries/iLLD/TC39B/Tricore/Ccu6/TimerWithTrigger \
Libraries/iLLD/TC39B/Tricore/Convctrl/Std \
Libraries/iLLD/TC39B/Tricore/Cpu/Irq \
Libraries/iLLD/TC39B/Tricore/Cpu/Std \
Libraries/iLLD/TC39B/Tricore/Cpu/Trap \
Libraries/iLLD/TC39B/Tricore/Dma/Dma \
Libraries/iLLD/TC39B/Tricore/Dma/Std \
Libraries/iLLD/TC39B/Tricore/Dts/Dts \
Libraries/iLLD/TC39B/Tricore/Dts/Std \
Libraries/iLLD/TC39B/Tricore/Ebu/BFlashSpansion \
Libraries/iLLD/TC39B/Tricore/Ebu/BFlashSt \
Libraries/iLLD/TC39B/Tricore/Ebu/Dram \
Libraries/iLLD/TC39B/Tricore/Ebu/Sram \
Libraries/iLLD/TC39B/Tricore/Ebu/Std \
Libraries/iLLD/TC39B/Tricore/Edsadc/Edsadc \
Libraries/iLLD/TC39B/Tricore/Edsadc/Std \
Libraries/iLLD/TC39B/Tricore/Emem/Std \
Libraries/iLLD/TC39B/Tricore/Eray/Eray \
Libraries/iLLD/TC39B/Tricore/Eray/Std \
Libraries/iLLD/TC39B/Tricore/Evadc/Adc \
Libraries/iLLD/TC39B/Tricore/Evadc/Std \
Libraries/iLLD/TC39B/Tricore/Fce/Crc \
Libraries/iLLD/TC39B/Tricore/Fce/Std \
Libraries/iLLD/TC39B/Tricore/Flash/Std \
Libraries/iLLD/TC39B/Tricore/Geth/Eth \
Libraries/iLLD/TC39B/Tricore/Geth/Std \
Libraries/iLLD/TC39B/Tricore/Gpt12/IncrEnc \
Libraries/iLLD/TC39B/Tricore/Gpt12/Std \
Libraries/iLLD/TC39B/Tricore/Gtm/Atom/Dtm_PwmHl \
Libraries/iLLD/TC39B/Tricore/Gtm/Atom/Pwm \
Libraries/iLLD/TC39B/Tricore/Gtm/Atom/PwmHl \
Libraries/iLLD/TC39B/Tricore/Gtm/Atom/Timer \
Libraries/iLLD/TC39B/Tricore/Gtm/Pwm \
Libraries/iLLD/TC39B/Tricore/Gtm/Std \
Libraries/iLLD/TC39B/Tricore/Gtm/Tim/In \
Libraries/iLLD/TC39B/Tricore/Gtm/Tim/Timer \
Libraries/iLLD/TC39B/Tricore/Gtm/Tom/Dtm_PwmHl \
Libraries/iLLD/TC39B/Tricore/Gtm/Tom/Pwm \
Libraries/iLLD/TC39B/Tricore/Gtm/Tom/PwmHl \
Libraries/iLLD/TC39B/Tricore/Gtm/Tom/Timer \
Libraries/iLLD/TC39B/Tricore/Gtm/Trig \
Libraries/iLLD/TC39B/Tricore/Hspdm/Std \
Libraries/iLLD/TC39B/Tricore/Hssl/Hssl \
Libraries/iLLD/TC39B/Tricore/Hssl/Std \
Libraries/iLLD/TC39B/Tricore/I2c/I2c \
Libraries/iLLD/TC39B/Tricore/I2c/Std \
Libraries/iLLD/TC39B/Tricore/Iom/Driver \
Libraries/iLLD/TC39B/Tricore/Iom/Iom \
Libraries/iLLD/TC39B/Tricore/Iom/Std \
Libraries/iLLD/TC39B/Tricore/Msc/Msc \
Libraries/iLLD/TC39B/Tricore/Msc/Std \
Libraries/iLLD/TC39B/Tricore/Mtu/Std \
Libraries/iLLD/TC39B/Tricore/Pms/Std \
Libraries/iLLD/TC39B/Tricore/Port/Io \
Libraries/iLLD/TC39B/Tricore/Port/Std \
Libraries/iLLD/TC39B/Tricore/Psi5/Psi5 \
Libraries/iLLD/TC39B/Tricore/Psi5/Std \
Libraries/iLLD/TC39B/Tricore/Psi5s/Psi5s \
Libraries/iLLD/TC39B/Tricore/Psi5s/Std \
Libraries/iLLD/TC39B/Tricore/Qspi/SpiMaster \
Libraries/iLLD/TC39B/Tricore/Qspi/SpiSlave \
Libraries/iLLD/TC39B/Tricore/Qspi/Std \
Libraries/iLLD/TC39B/Tricore/Rif/Rif \
Libraries/iLLD/TC39B/Tricore/Rif/Std \
Libraries/iLLD/TC39B/Tricore/Scu/Std \
Libraries/iLLD/TC39B/Tricore/Sdmmc/Emmc \
Libraries/iLLD/TC39B/Tricore/Sdmmc/Sd \
Libraries/iLLD/TC39B/Tricore/Sdmmc/Std \
Libraries/iLLD/TC39B/Tricore/Sent/Sent \
Libraries/iLLD/TC39B/Tricore/Sent/Std \
Libraries/iLLD/TC39B/Tricore/Smu/Smu \
Libraries/iLLD/TC39B/Tricore/Smu/Std \
Libraries/iLLD/TC39B/Tricore/Spu/Std \
Libraries/iLLD/TC39B/Tricore/Src/Std \
Libraries/iLLD/TC39B/Tricore/Stm/Std \
Libraries/iLLD/TC39B/Tricore/Stm/Timer \
Libraries/iLLD/TC39B/Tricore/_Impl \
Libraries/iLLD/TC39B/Tricore/_Lib/DataHandling \
Libraries/iLLD/TC39B/Tricore/_Lib/InternalMux \
Libraries/iLLD/TC39B/Tricore/_PinMap \

